SECRET_KEY = 'your-secret'

SQLALCHEMY_DATABASE_URI = 'postgresql://each:Ellesmera2006@185.122.59.110:5434/OAuth_db'
OAUTH_CACHE_DIR = '_cache'

GOOGLE_CLIENT_KEY = ''
GOOGLE_CLIENT_SECRET = ''

TWITTER_CLIENT_KEY = ''
TWITTER_CLIENT_SECRET = ''

GITHUB_CLIENT_KEY = ''
GITHUB_CLIENT_SECRET = ''

FACEBOOK_CLIENT_KEY = ''
FACEBOOK_CLIENT_SECRET = ''
